<%@ Page Title="" Language="C#" MasterPageFile="~/site.master" AutoEventWireup="true" CodeFile="fm_claimtrack.aspx.cs" Inherits="fm_claimtrack" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <link href="css/anekabutton.css" rel="stylesheet" />
    <script src="js/jquery-1.9.1.min.js"></script>
    <link href="css/bootstrap.min.css" rel="stylesheet" />
    <script src="js/bootstrap.min.js"></script>
    <style type="text/css">
        .nodeLevel1 {
            font: 14px Arial,Sans-Serif;
            border: double 1px gray;
            background: red url(image/cyan.png) repeat-x top left;
            height: 25px;
            width: 100px;
            padding-left: 5px;
        }

        .nodeLevel2 {
            font: 12px Arial,Sans-Serif;
            border: double 1px gray;
            margin: 0px;
            padding-left: 10px;
            background: red url(image/gradient_orange.JPG) repeat-x top left;
            height: 25px;
            width: 100px;
        }

        .nodeLevel3 {
            font: 10px Arial,Sans-Serif;
            border: double 1px gray;
            margin: 0px;
            padding-left: 15px;
            background: red url(image/grayMenuBar.PNG) repeat-x top left;
            height: 25px;
            width: 100px;
        }
    </style>
    <script>
        function PropSelected(sender, e) {
            $get('<%=hdprop.ClientID%>').value = e.get_value();
        }
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:HiddenField ID="hdprop" runat="server" />
    <div class="container">
        <div class="form-horizontal">
            <h3 class="jajarangenjang">Claim TRACK</h3>
            <div class="h-divider"></div>
            <div class="form-group">
                <label class="control-label col-md-1 ">Proposal:</label>
                <div class="col-md-7">
                            <asp:TextBox ID="txprop" runat="server" CssClass="form-control input-md" Height="100%" Width="100%"></asp:TextBox>
                            <div id="divwidth1" style="font-size: small; font-family: Calibri; position: absolute;"></div>
                            <asp:AutoCompleteExtender OnClientItemSelected="PropSelected" ID="txprop_AutoCompleteExtender" runat="server" ServiceMethod="GetCompletionList" TargetControlID="txprop" UseContextKey="True" MinimumPrefixLength="1" FirstRowSelected="false" EnableCaching="false" CompletionSetCount="1" CompletionInterval="10" CompletionListElementID="divwidth">
                            </asp:AutoCompleteExtender>                   
                </div>
                <div class="col-md-7">
                    <asp:Button ID="btcheck" runat="server" Text="Track" CssClass="btn-default form-control-static button2 print" OnClick="btcheck_Click" />
                </div>

            </div>
            <div class="nav"><asp:TreeView ID="trclaimtrack" runat="server" Style="width: 100%;margin-right:5px;margin-left:5px;" AutoGenerateDataBindings="False" >
        <SelectedNodeStyle BackColor="#3399FF" ForeColor="#FFFF66" />
    </asp:TreeView></div>
        </div>
    </div>
    
</asp:Content>

